# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffe4e6895e2e63df23f5a0b38e063f379ade8c37b2c064363f29f15eb1953bb7f03ea94963d6db9b2e6407d65ea5629f322d63ae4c166c55809066e874b34918

test:
  secret_key_base: 635af6ed93d6d3402829b5351074a0d0fd148a43d4971208dd9d3ac33d8564b13cd828565c045b1a1939a59d5ae4945f78fe14169c181f34b551e2be641d3fbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
